# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YouTubeClone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 7.0'
  pod "youtube-ios-player-helper"
  pod 'FloatingPanel'
  # Pods for YouTubeClone

end
